config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
    controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  scope "(:locale)", locale: /en|vi/ do
  	root "static_pages#home"
  	resources :products
    resources :product_orders
    resources :shops, only: [:index, :show]
    namespace :shops do
      resources :products
      resources :categories
    end
    namespace :admin do
      root "dashboard#index"
    end

    resources :conversations do
      resources :messages
    end

    resources :users
    resources :addresses
    resources :carts
    resources :checkouts
    resources :reviews
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
  has_many :user_categories
  has_many :users, through: :user_categories

  validates :name, presence:true, uniqueness:true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User.name
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User.name
  validates :sender_id, uniqueness: {scope: :recipient_id}

  scope :involving, -> (user) do
   where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
 end

 scope :between, -> (sender_id,recipient_id) do
   where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
 end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  validates_presence_of :body, :conversation_id, :user_id
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :product_orders
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_orders, dependent: :destroy
  has_many :orders, through: :product_orders
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories, dependent: :destroy
  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :blank?

  validates :name, presence:true
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ },
    numericality: { greater_than: 0, less_than: 1000000}
  validates :sale_price, presence: true, allow_blank: true, format: { with: /\A\d+(?:\.\d{2})?\z/ },
    numericality: { greater_than: 0, less_than: 1000000}
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  has_many :orders
  has_many :reviews, dependent: :destroy
  has_many :comments
  has_many :addresses, dependent: :destroy
  accepts_nested_attributes_for :addresses
  has_many :addresses
  has_many :user_categories
  has_many :categories, through: :user_categories
  has_one :image, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :image
  delegate :address, to: :image, prefix: true, allow_nil: true

  def self.new_with_session params, session
    super.tap do |user|
      if data = session["devise.facebook_data"] &&
        session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/models/user_category.rb
class UserCategory < ApplicationRecord
  belongs_to :category
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token


  layout false

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    render json: { conversation_id: @conversation.id }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def create
    @conversation = Conversation.find(params[:conversation_id])
    @message = @conversation.messages.build(message_params)
    @message.user_id = current_user.id
    @message.save!
    @path = conversation_path(@conversation)
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/shops/categories_controller.rb
class Shops::CategoriesController < ApplicationController
  before_action :load_category, except: [:index, :new, :create]
  def index
    @category = current_user.categories.all
  end

  def new
    @category = Category.new
  end

  def create
    if current_user.categories.create category_params
      flash[:success] = "Tạo thành công"
      redirect_to shops_categories_path
    else
      render :new
    end
  end

  def show;end

  def edit; end

  def update
    if @category.update category_params
      redirect_to shops_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to shops_categories_path
  end

  private

  def category_params
    params.require(:category).permit :name
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
    flash[:danger] = "Chuyên mục không tồn tại"
    redirect_to shops_categories_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def self_or_other(message)
    message.user == current_user ? "self" : "other"
  end

  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @reciever.name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
  <br clear="all"/>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => {id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>

<%= subscribe_to conversation_path(@conversation) %>

app/views/messages/_message.html.erb
<li class="<%=  self_or_other(message) %>">
  <div class="avatar">
    <%# byebug %>
    <% if self_or_other(message) == "self" %>
      <%= image_tag "avatar-default.png" %>
    <% else %>
      <%= image_tag "avatar-default1.png" %>
    <% end %>
  </div>
  <div class="chatboxmessagecontent">
    <p><%= message.body %></p>
    <time datetime="<%= message.created_at %>" title="<%= message.created_at.strftime("%d %b  %Y at %I:%M%p") %>">
      <%= message_interlocutor(message).name %> • <%= message.created_at.strftime("%H:%M %p") %>
    </time>
  </div>
</li>

app/views/messages/create.js.erb
<% publish_to @path do %>
    var id = "<%= @conversation.id %>";
    var chatbox = $("#chatbox_" + id + " .chatboxcontent");
    var sender_id = "<%= @message.user.id %>";
    var reciever_id = $('meta[name=user-id]').attr("content");

    chatbox.append("<%= j render( partial: @message ) %>");
    chatbox.scrollTop(chatbox[0].scrollHeight);

    if(sender_id != reciever_id){
      chatBox.chatWith(id);
        chatbox.children().last().removeClass("self").addClass("other");
      chatbox.scrollTop(chatbox[0].scrollHeight);
        chatBox.notify();
    }
<% end %>

app/views/shops/categories/edit.html.erb
<div class="new shop-content">
  <div class="flex-row container">
    <div class="col-md-12">
    <%= form_for [:shops, @category] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
      <div class="box-body pad">
        <div class="form-group">
          <div class="form_new_product">
            <h2><%= t(".edit_categories") %></h2>
            <div class="form-content mb-3">
              <label class="col-md-2 control-label"> <%= t(".cat_name") %>:
                <span class="required">
                  *
                </span>
              </label>
              <div class="col-md-10 mg-10">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
            <%= f.submit t(".update"), class: "btn btn-success" %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/shops/categories/index.html.erb
<div class="shop-categories">
  <div class="flex-row container">
    <div class="col-md-12">
      <div class="shop-categories-list">
        <h3><%= t(".display_name") %></h3>
        <div class="item-collection__list">
          <div class="item-collection__list-header">
            <%= link_to new_shops_category_path, class: "add-ember-view" do %>
              <i class="fa fa-plus-square-o" aria-hidden="true"></i>
              <%= t(".button_addnew") %>
            <% end %>
            <span>
              <i class="fa fa-list" aria-hidden="true"></i> <%= t(".my_catalog") %>
            </span>
            <div class="my-catelog">
              <% @category.each do |category| %>
                <table>
                  <tbody>
                    <tr>
                      <td class="name"><%= category.name %></td>
                      <td class="details">
                        <%= link_to  t(".details"), edit_shops_category_path(category) %>
                      </td>
                      <td class="delete">
                        <%= link_to shops_category_path(category), data: { confirm: "Are you sure?" }, method: :delete do %>
                          <i class="fa fa-trash-o" aria-hidden="true"></i>
                        <% end %>
                      </td>
                    </tr>
                  </tbody>
                </table>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shops/categories/new.html.erb
<div class="new shop-content">
  <div class="flex-row container">
    <div class="col-md-12">
    <%= form_for [:shops, @category] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
      <div class="box-body pad">
        <div class="form-group">
          <div class="form_new_product">
            <h2><%= t(".add_new_cat") %></h2>
            <div class="form-content mb-3">
              <label class="col-md-2 control-label"> <%= t(".cat_name") %>:
                <span class="required">
                  *
                </span>
              </label>
              <div class="col-md-10 mg-10">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
            <%= f.submit t(".add_new"), class: "btn btn-success" %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<main id ="main" class="main-content">
  <div class="flex-row container">
    <div class="col-md-12">
      <h2 class="center shop-old-title">
        <%= t(".welcome") %>
      </h2>
      <div class="subtitle center">
        <p><%= t(".description") %></p>
      </div>
      <div class="content">
        <div class="button-cotent center clearfix">
          <div class="button">
            <%= link_to shops_products_path, class: "shop-button bg-blue" do %>
              <i class="fa fa-gift" aria-hidden="true"></i>
            <% end %>
            <div class="sr"><%= t(".product_title") %></div>
          </div>
          <div class="button">
            <%= link_to shops_categories_path, class: "shop-button bg-oranges" do %>
              <i class="fa fa-list" aria-hidden="true"></i>
            <% end %>
            <div class="sr"><%= t(".category_title") %></div>
          </div>
          <div class="button">
            <a href="#" class="shop-button bg-pink" target="_blank">
              <i class="fa fa-first-order" aria-hidden="true"></i>
            </a>
            <div class="sr"><%= t(".oder") %></div>
          </div>
          <div class="button">
            <a href="#" class="shop-button bg-blue-sky" target="_blank">
              <i class="fa fa-pie-chart" aria-hidden="true"></i>
            </a>
            <div class="sr"><%= t(".statistical") %></div>
          </div>
          <div class="button">
            <a href="#" class="shop-button bg-yellow" target="_blank">
              <i class="fa fa-money" aria-hidden="true"></i>
            </a>
            <div class="sr"><%= t(".revenue") %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<div class="container" style="min-height: 300px;">
  <% @users.each_with_index do |user, index| %>
      <tr>
        <td><%= index +=1 %></td>
        <td><%= user.name %></td>
        <td>
          <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                      "data-sid" => current_user.id, "data-rip" => user.id %>
        </td>
      </tr>
  <% end %>

</div>